import type { NamedAPIResourceList } from 'pokedex-promise-v2'

const species: NamedAPIResourceList = {
  count: 1025,
  next: null,
  previous: null,
  results: [
    {
      name: 'bulbasaur',
      url: 'https://pokeapi.co/api/v2/pokemon-species/1/',
    },
    {
      name: 'charizard',
      url: 'https://pokeapi.co/api/v2/pokemon-species/6/',
    },
    {
      name: 'pikachu',
      url: 'https://pokeapi.co/api/v2/pokemon-species/25/',
    },
    {
      name: 'nidoran-m',
      url: 'https://pokeapi.co/api/v2/pokemon-species/32/',
    },
    {
      name: 'ninetales',
      url: 'https://pokeapi.co/api/v2/pokemon-species/38/',
    },
    {
      name: 'farfetchd',
      url: 'https://pokeapi.co/api/v2/pokemon-species/83/',
    },
    {
      name: 'mr-mime',
      url: 'https://pokeapi.co/api/v2/pokemon-species/122/',
    },
    {
      name: 'eevee',
      url: 'https://pokeapi.co/api/v2/pokemon-species/133/',
    },
    {
      name: 'moltres',
      url: 'https://pokeapi.co/api/v2/pokemon-species/146/',
    },
    {
      name: 'mewtwo',
      url: 'https://pokeapi.co/api/v2/pokemon-species/150/',
    },
    {
      name: 'mew',
      url: 'https://pokeapi.co/api/v2/pokemon-species/151/',
    },
    {
      name: 'unown',
      url: 'https://pokeapi.co/api/v2/pokemon-species/201/',
    },
    {
      name: 'shuckle',
      url: 'https://pokeapi.co/api/v2/pokemon-species/213/',
    },
    {
      name: 'blissey',
      url: 'https://pokeapi.co/api/v2/pokemon-species/242/',
    },
    {
      name: 'swampert',
      url: 'https://pokeapi.co/api/v2/pokemon-species/260/',
    },
    {
      name: 'wurmple',
      url: 'https://pokeapi.co/api/v2/pokemon-species/265/',
    },
    {
      name: 'shedinja',
      url: 'https://pokeapi.co/api/v2/pokemon-species/292/',
    },
    {
      name: 'aggron',
      url: 'https://pokeapi.co/api/v2/pokemon-species/306/',
    },
    {
      name: 'rayquaza',
      url: 'https://pokeapi.co/api/v2/pokemon-species/384/',
    },
    {
      name: 'deoxys',
      url: 'https://pokeapi.co/api/v2/pokemon-species/386/',
    },
    {
      name: 'gastrodon',
      url: 'https://pokeapi.co/api/v2/pokemon-species/423/',
    },
    {
      name: 'garchomp',
      url: 'https://pokeapi.co/api/v2/pokemon-species/445/',
    },
    {
      name: 'glaceon',
      url: 'https://pokeapi.co/api/v2/pokemon-species/471/',
    },
    {
      name: 'gallade',
      url: 'https://pokeapi.co/api/v2/pokemon-species/475/',
    },
    {
      name: 'rotom',
      url: 'https://pokeapi.co/api/v2/pokemon-species/479/',
    },
    {
      name: 'dialga',
      url: 'https://pokeapi.co/api/v2/pokemon-species/483/',
    },
    {
      name: 'arceus',
      url: 'https://pokeapi.co/api/v2/pokemon-species/493/',
    },
    {
      name: 'jellicent',
      url: 'https://pokeapi.co/api/v2/pokemon-species/593/',
    },
    {
      name: 'kyurem',
      url: 'https://pokeapi.co/api/v2/pokemon-species/646/',
    },
    {
      name: 'chesnaught',
      url: 'https://pokeapi.co/api/v2/pokemon-species/652/',
    },
    {
      name: 'greninja',
      url: 'https://pokeapi.co/api/v2/pokemon-species/658/',
    },
    {
      name: 'talonflame',
      url: 'https://pokeapi.co/api/v2/pokemon-species/663/',
    },
    {
      name: 'vivillon',
      url: 'https://pokeapi.co/api/v2/pokemon-species/666/',
    },
    {
      name: 'meowstic',
      url: 'https://pokeapi.co/api/v2/pokemon-species/678/',
    },
    {
      name: 'aegislash',
      url: 'https://pokeapi.co/api/v2/pokemon-species/681/',
    },
    {
      name: 'xerneas',
      url: 'https://pokeapi.co/api/v2/pokemon-species/716/',
    },
    {
      name: 'yveltal',
      url: 'https://pokeapi.co/api/v2/pokemon-species/717/',
    },
    {
      name: 'zygarde',
      url: 'https://pokeapi.co/api/v2/pokemon-species/718/',
    },
    {
      name: 'volcanion',
      url: 'https://pokeapi.co/api/v2/pokemon-species/721/',
    },
    {
      name: 'trumbeak',
      url: 'https://pokeapi.co/api/v2/pokemon-species/732/',
    },
    {
      name: 'crabominable',
      url: 'https://pokeapi.co/api/v2/pokemon-species/740/',
    },
    {
      name: 'rockruff',
      url: 'https://pokeapi.co/api/v2/pokemon-species/744/',
    },
    {
      name: 'salazzle',
      url: 'https://pokeapi.co/api/v2/pokemon-species/758/',
    },
    {
      name: 'silvally',
      url: 'https://pokeapi.co/api/v2/pokemon-species/773/',
    },
    {
      name: 'minior',
      url: 'https://pokeapi.co/api/v2/pokemon-species/774/',
    },
    {
      name: 'lunala',
      url: 'https://pokeapi.co/api/v2/pokemon-species/792/',
    },
    {
      name: 'necrozma',
      url: 'https://pokeapi.co/api/v2/pokemon-species/800/',
    },
    {
      name: 'cramorant',
      url: 'https://pokeapi.co/api/v2/pokemon-species/845/',
    },
    {
      name: 'hatterene',
      url: 'https://pokeapi.co/api/v2/pokemon-species/858/',
    },
    {
      name: 'alcremie',
      url: 'https://pokeapi.co/api/v2/pokemon-species/869/',
    },
    {
      name: 'indeedee',
      url: 'https://pokeapi.co/api/v2/pokemon-species/876/',
    },
    {
      name: 'morpeko',
      url: 'https://pokeapi.co/api/v2/pokemon-species/877/',
    },
    {
      name: 'eternatus',
      url: 'https://pokeapi.co/api/v2/pokemon-species/890/',
    },
    {
      name: 'calyrex',
      url: 'https://pokeapi.co/api/v2/pokemon-species/898/',
    },
    {
      name: 'oinkologne',
      url: 'https://pokeapi.co/api/v2/pokemon-species/916/',
    },
    {
      name: 'maushold',
      url: 'https://pokeapi.co/api/v2/pokemon-species/925/',
    },
    {
      name: 'tatsugiri',
      url: 'https://pokeapi.co/api/v2/pokemon-species/978/',
    },
    {
      name: 'dudunsparce',
      url: 'https://pokeapi.co/api/v2/pokemon-species/982/',
    },
    {
      name: 'iron-hands',
      url: 'https://pokeapi.co/api/v2/pokemon-species/992/',
    },
    {
      name: 'koraidon',
      url: 'https://pokeapi.co/api/v2/pokemon-species/998/',
    },
    {
      name: 'miraidon',
      url: 'https://pokeapi.co/api/v2/pokemon-species/999/',
    },
    {
      name: 'roaring-moon',
      url: 'https://pokeapi.co/api/v2/pokemon-species/1005/',
    },
    {
      name: 'chi-yu',
      url: 'https://pokeapi.co/api/v2/pokemon-species/1004/',
    },
    {
      name: 'pecharunt',
      url: 'https://pokeapi.co/api/v2/pokemon-species/1025/',
    },
  ],
}

// export const pokeapi = new Pokedex({
//   // 3 months
//   cacheLimit: 1000 * 60 * 60 * 24 * 30 * 3,
//   // 5 minutes
//   timeout: 300000,
// })

export const getTestSpeciesList = async () => {
  await new Promise((resolve) => setTimeout(resolve, 10))
  return species
}

const items = [
  'master-ball',
  'ultra-ball',
  'great-ball',
  'poke-ball',
  'safari-ball',
  'net-ball',
  'dive-ball',
  'nest-ball',
  'repeat-ball',
  'timer-ball',
  'luxury-ball',
  'premier-ball',
  'dusk-ball',
  'heal-ball',
  'quick-ball',
  'cherish-ball',
  'potion',
  'antidote',
  'burn-heal',
  'ice-heal',
  'awakening',
  'paralyze-heal',
  'full-restore',
  'max-potion',
  'hyper-potion',
  'super-potion',
  'full-heal',
  'revive',
  'max-revive',
  'fresh-water',
  'soda-pop',
  'lemonade',
  'moomoo-milk',
  'energy-powder',
  'energy-root',
  'heal-powder',
  'revival-herb',
  'ether',
  'max-ether',
  'elixir',
  'max-elixir',
  'hp-up',
  'protein',
  'iron',
  'carbos',
  'calcium',
  'rare-candy',
  'pp-up',
  'zinc',
  'pp-max',
  'guard-spec',
  'dire-hit',
  'x-attack',
  'x-defense',
  'x-speed',
  'x-accuracy',
  'x-sp-atk',
  'x-sp-def',
  'poke-doll',
  'super-repel',
  'max-repel',
  'escape-rope',
  'repel',
  'sun-stone',
  'moon-stone',
  'fire-stone',
  'thunder-stone',
  'water-stone',
  'leaf-stone',
  'tiny-mushroom',
  'big-mushroom',
  'pearl',
  'big-pearl',
  'stardust',
  'star-piece',
  'nugget',
  'honey',
  'rare-bone',
  'shiny-stone',
  'dusk-stone',
  'dawn-stone',
  'oval-stone',
  'odd-keystone',
  'griseous-orb',
  'adamant-orb',
  'lustrous-orb',
  'cheri-berry',
  'chesto-berry',
  'pecha-berry',
  'rawst-berry',
  'aspear-berry',
  'leppa-berry',
  'oran-berry',
  'persim-berry',
  'lum-berry',
  'sitrus-berry',
  'figy-berry',
  'wiki-berry',
  'mago-berry',
  'aguav-berry',
  'iapapa-berry',
  'razz-berry',
  'bluk-berry',
  'nanab-berry',
  'wepear-berry',
  'pinap-berry',
  'pomeg-berry',
  'kelpsy-berry',
  'qualot-berry',
  'hondew-berry',
  'grepa-berry',
  'tamato-berry',
  'cornn-berry',
  'magost-berry',
  'rabuta-berry',
  'nomel-berry',
  'spelon-berry',
  'pamtre-berry',
  'watmel-berry',
  'durin-berry',
  'belue-berry',
  'occa-berry',
  'passho-berry',
  'wacan-berry',
  'rindo-berry',
  'yache-berry',
  'chople-berry',
  'kebia-berry',
  'shuca-berry',
  'coba-berry',
  'payapa-berry',
  'tanga-berry',
  'charti-berry',
  'kasib-berry',
  'haban-berry',
  'colbur-berry',
  'babiri-berry',
  'chilan-berry',
  'liechi-berry',
  'ganlon-berry',
  'salac-berry',
  'petaya-berry',
  'apicot-berry',
  'lansat-berry',
  'starf-berry',
  'enigma-berry',
  'micle-berry',
  'custap-berry',
  'jaboca-berry',
  'rowap-berry',
  'bright-powder',
  'white-herb',
  'exp-share',
  'quick-claw',
  'soothe-bell',
  'mental-herb',
  'choice-band',
  'kings-rock',
  'silver-powder',
  'amulet-coin',
  'cleanse-tag',
  'soul-dew',
  'smoke-ball',
  'everstone',
  'focus-band',
  'lucky-egg',
  'scope-lens',
  'metal-coat',
  'leftovers',
  'dragon-scale',
  'light-ball',
  'soft-sand',
  'hard-stone',
  'miracle-seed',
  'black-glasses',
  'black-belt',
  'magnet',
  'mystic-water',
  'sharp-beak',
  'poison-barb',
  'never-melt-ice',
  'spell-tag',
  'twisted-spoon',
  'charcoal',
  'dragon-fang',
  'silk-scarf',
  'up-grade',
  'shell-bell',
  'sea-incense',
  'lax-incense',
  'wide-lens',
  'muscle-band',
  'wise-glasses',
  'expert-belt',
  'light-clay',
  'life-orb',
  'power-herb',
  'toxic-orb',
  'flame-orb',
  'focus-sash',
  'zoom-lens',
  'metronome',
  'iron-ball',
  'lagging-tail',
  'destiny-knot',
  'black-sludge',
  'icy-rock',
  'smooth-rock',
  'heat-rock',
  'damp-rock',
  'grip-claw',
  'choice-scarf',
  'sticky-barb',
  'power-bracer',
  'power-belt',
  'power-lens',
  'power-band',
  'power-anklet',
  'power-weight',
  'shed-shell',
  'big-root',
  'choice-specs',
  'flame-plate',
  'splash-plate',
  'zap-plate',
  'meadow-plate',
  'icicle-plate',
  'fist-plate',
  'toxic-plate',
  'earth-plate',
  'sky-plate',
  'mind-plate',
  'insect-plate',
  'stone-plate',
  'spooky-plate',
  'draco-plate',
  'dread-plate',
  'iron-plate',
  'odd-incense',
  'rock-incense',
  'full-incense',
  'wave-incense',
  'rose-incense',
  'luck-incense',
  'pure-incense',
  'protector',
  'electirizer',
  'magmarizer',
  'dubious-disc',
  'reaper-cloth',
  'razor-claw',
  'razor-fang',
  'tm-dark',
  'tm-dragon',
  'tm-psychic',
  'tm-normal',
  'tm-poison',
  'tm-ice',
  'tm-fighting',
  'tm-fire',
  'tm-water',
  'tm-grass',
  'tm-rock',
  'tm-electric',
  'tm-ground',
  'tm-ghost',
  'tm-steel',
  'tm-bug',
  'tm-flying',
  'gracidea',
  'red-apricorn',
  'blue-apricorn',
  'yellow-apricorn',
  'green-apricorn',
  'pink-apricorn',
  'white-apricorn',
  'black-apricorn',
  'fast-ball',
  'level-ball',
  'lure-ball',
  'heavy-ball',
  'love-ball',
  'friend-ball',
  'moon-ball',
  'sport-ball',
  'park-ball',
  'prism-scale',
  'eviolite',
  'float-stone',
  'rocky-helmet',
  'air-balloon',
  'red-card',
  'ring-target',
  'binding-band',
  'absorb-bulb',
  'cell-battery',
  'eject-button',
  'normal-gem',
  'health-wing',
  'muscle-wing',
  'resist-wing',
  'genius-wing',
  'clever-wing',
  'swift-wing',
  'pretty-wing',
  'dream-ball',
  'balm-mushroom',
  'big-nugget',
  'pearl-string',
  'comet-shard',
  'oval-charm',
  'shiny-charm',
  'reveal-glass',
  'weakness-policy',
  'assault-vest',
  'pixie-plate',
  'ability-capsule',
  'luminous-moss',
  'snowball',
  'safety-goggles',
  'roseli-berry',
  'kee-berry',
  'maranga-berry',
  'tm-fairy',
  'adventure-rules',
  'lumiose-galette',
  'shalour-sable',
  'prison-bottle',
  'bottle-cap',
  'gold-bottle-cap',
  'adrenaline-orb',
  'ice-stone',
  'beast-ball',
  'red-nectar',
  'yellow-nectar',
  'pink-nectar',
  'purple-nectar',
  'terrain-extender',
  'protective-pads',
  'electric-seed',
  'psychic-seed',
  'misty-seed',
  'grassy-seed',
  'rusted-sword',
  'rusted-shield',
  'strawberry-sweet',
  'love-sweet',
  'berry-sweet',
  'clover-sweet',
  'flower-sweet',
  'star-sweet',
  'ribbon-sweet',
  'sweet-apple',
  'tart-apple',
  'throat-spray',
  'eject-pack',
  'heavy-duty-boots',
  'blunder-policy',
  'room-service',
  'utility-umbrella',
  'exp-candy-xs',
  'exp-candy-s',
  'exp-candy-m',
  'exp-candy-l',
  'exp-candy-xl',
  'lonely-mint',
  'adamant-mint',
  'naughty-mint',
  'brave-mint',
  'bold-mint',
  'impish-mint',
  'lax-mint',
  'relaxed-mint',
  'modest-mint',
  'mild-mint',
  'rash-mint',
  'quiet-mint',
  'calm-mint',
  'gentle-mint',
  'careful-mint',
  'sassy-mint',
  'timid-mint',
  'hasty-mint',
  'jolly-mint',
  'naive-mint',
  'serious-mint',
  'cracked-pot',
  'chipped-pot',
  'catching-charm',
  'rotom-catalog',
  'galarica-twig',
  'galarica-cuff',
  'exp-charm',
  'mark-charm',
  'reins-of-unity',
  'galarica-wreath',
  'ability-patch',
  'black-augurite',
  'peat-block',
  'adamant-crystal',
  'lustrous-globe',
  'griseous-core',
  'blank-plate',
  'strange-ball',
  'legend-plate',
  'rotom-phone',
  'sandwich',
  'tera-orb',
  'scarlet-book',
  'violet-book',
  'kofus-wallet',
  'tiny-bamboo-shoot',
  'big-bamboo-shoot',
  'scroll-of-darkness',
  'scroll-of-waters',
  'scarlet-vein',
  'violet-rune',
  'malicious-armor',
  'normal-tera-shard',
  'fire-tera-shard',
  'water-tera-shard',
  'electric-tera-shard',
  'grass-tera-shard',
  'ice-tera-shard',
  'fighting-tera-shard',
  'poison-tera-shard',
  'ground-tera-shard',
  'flying-tera-shard',
  'psychic-tera-shard',
  'bug-tera-shard',
  'rock-tera-shard',
  'ghost-tera-shard',
  'dragon-tera-shard',
  'dark-tera-shard',
  'steel-tera-shard',
  'fairy-tera-shard',
  'booster-energy',
  'ability-shield',
  'clear-amulet',
  'mirror-herb',
  'punching-glove',
  'covert-cloak',
  'loaded-dice',
  'baguette',
  'mayonnaise',
  'ketchup',
  'mustard',
  'butter',
  'peanut-butter',
  'salt',
  'pepper',
  'yogurt',
  'whipped-cream',
  'cream-cheese',
  'jam',
  'marmalade',
  'olive-oil',
  'vinegar',
  'sweet-herba-mystica',
  'salty-herba-mystica',
  'sour-herba-mystica',
  'bitter-herba-mystica',
  'spicy-herba-mystica',
  'lettuce',
  'tomato',
  'cherry-tomatoes',
  'cucumber',
  'pickle',
  'onion',
  'red-onion',
  'green-bell-pepper',
  'red-bell-pepper',
  'yellow-bell-pepper',
  'avocado',
  'bacon',
  'ham',
  'prosciutto',
  'chorizo',
  'herbed-sausage',
  'hamburger',
  'klawf-stick',
  'smoked-fillet',
  'fried-fillet',
  'egg',
  'potato-tortilla',
  'tofu',
  'rice',
  'noodles',
  'potato-salad',
  'cheese',
  'banana',
  'strawberry',
  'apple',
  'kiwi',
  'pineapple',
  'tm-material',
  'auspicious-armor',
  'leaders-crest',
  'fairy-feather',
  'syrupy-apple',
  'unremarkable-teacup',
  'masterpiece-teacup',
  'teal-mask',
  'cornerstone-mask',
  'wellspring-mask',
  'hearthflame-mask',
  'teal-style-card',
  'crystal-cluster',
  'health-mochi',
  'muscle-mochi',
  'resist-mochi',
  'genius-mochi',
  'clever-mochi',
  'swift-mochi',
  'roto-stick',
  'fresh-start-mochi',
  'glimmering-charm',
  'metal-alloy',
  'stellar-tera-shard',
]

export const itemResourceList: NamedAPIResourceList = {
  count: items.length,
  next: null,
  previous: null,
  results: items.map((slug) => ({
    name: slug,
    url: `https://pokeapi.co/api/v2/item/${slug}/`,
  })),
}
