export const excludedVariants = [
  // Pikachu costumes
  'pikachu-rock-star',
  'pikachu-belle',
  'pikachu-pop-star',
  'pikachu-phd',
  'pikachu-libre',
  'pikachu-cosplay',
  // Zygarde power constructs
  'zygarde-50-power-construct',
  'zygarde-10-power-construct',
  // Minior duplicates with no unique sprites
  'minior-orange-meteor',
  'minior-yellow-meteor',
  'minior-green-meteor',
  'minior-blue-meteor',
  'minior-indigo-meteor',
  'minior-violet-meteor',
  // Eternatus story battle
  'eternatus-eternamax',
  // Gigantamax forms
  'charizard-gmax',
  'butterfree-gmax',
  'pikachu-gmax',
  'meowth-gmax',
  'machamp-gmax',
  'gengar-gmax',
  'kingler-gmax',
  'lapras-gmax',
  'eevee-gmax',
  'snorlax-gmax',
  'garbodor-gmax',
  'melmetal-gmax',
  'corvonite-gmax',
  'orbeetle-gmax',
  'drednaw-gmax',
  'coalossal-gmax',
  'flapple-gmax',
  'appletun-gmax',
  'sandaconda-gmax',
  'toxtricity-amped-gmax',
  'toxtricity-low-key-gmax',
  'centiskorch-gmax',
  'hatterene-gmax',
  'grimmsnarl-gmax',
  'alcremie-gmax',
  'copperajah-gmax',
  'duraludon-gmax',
  'venusaur-gmax',
  'blastoise-gmax',
  'rillaboom-gmax',
  'cinderace-gmax',
  'inteleon-gmax',
  'urshifu-single-strike-gmax',
  'urshifu-rapid-strike-gmax',
]

export const excludedForms = [
  // Unobtainable Arceus type
  'arceus-unknown',
  // Silvally type forms do not have sprites
  'silvally-normal',
  'silvally-fighting',
  'silvally-flying',
  'silvally-poison',
  'silvally-ground',
  'silvally-rock',
  'silvally-bug',
  'silvally-ghost',
  'silvally-steel',
  'silvally-fire',
  'silvally-water',
  'silvally-grass',
  'silvally-electric',
  'silvally-psychic',
  'silvally-ice',
  'silvally-dragon',
  'silvally-dark',
  'silvally-fairy',
]
